### ISSUE TITLE
How do I use pymediasoup to get audio data from the mediasoup server?

### ISSUE THREAD

**Issue by jacobtang** [skymaze/pymediasoup#10]
[mediasoup.py](https://github.com/skymaze/pymediasoup/blob/main/examples/mediasoup.py)
The example can use "record-to" command to save media file when get get media data from the mediasoup server , but can i get the raw audio/video callback data for for further use? not to record or playback by the system directly.
Thanks!

**Comment by skymaze** [comment]
You can handle the track manually [MediaStreamTrack](https://aiortc.readthedocs.io/en/latest/api.html#aiortc.MediaStreamTrack)

**Comment by jacobtang** [comment]
class MyAudioTrack(MediaStreamTrack):
    def __init__(self, track):
        super().__init__()  # don't forget this!
        self.track = track

    async def recv(self):
        if isinstance(self.track, AudioStreamTrack):
            frame = await self.track.recv()
            ......

    async def consume(self, id, producerId, kind, rtpParameters):
        if self._recvTransport == None:
            await self.createRecvTransport()
        consumer: Consumer = await self._recvTransport.consume(
            id=id,
            producerId=producerId,
            kind=kind,
            rtpParameters=rtpParameters
        )
        if consumer.track.kind == "audio":
            self._track = MyAudioTrack(consumer.track)

**Comment by jacobtang** [comment]
Can I customize `MyAudioTrack` to obtain audio data from the callback of the `consumer`'s `track`?
class MyAudioTrack(MediaStreamTrack):
    def __init__(self, track):
        super().__init__()  
        self.track = track

    async def recv(self):
        if isinstance(self.track, AudioStreamTrack):
            frame = await self.track.recv()
            ......
            
     async def consume(self, id, producerId, kind, rtpParameters):
        if self._recvTransport == None:
            await self.createRecvTransport()
        consumer: Consumer = await self._recvTransport.consume(
            id=id,
            producerId=producerId,
            kind=kind,
            rtpParameters=rtpParameters
        )
        if consumer.track.kind == "audio":
            self._track = MyAudioTrack(consumer.track)

**Comment by skymaze** [comment]
You can implement a media processing class [MediaRecorder](https://github.com/aiortc/aiortc/blob/537b79df78e32888433e3a40dd93b85ef55539c5/src/aiortc/contrib/media.py#L402) , then use an instance of your class here [demo](https://github.com/skymaze/pymediasoup/blob/3689c87670b8a6786f940778d3a1b53e546c4dde/examples/mediasoup.py#L358)
