### ISSUE TITLE
Can multiple audioProducers or videoProducers be supported?

### ISSUE THREAD

**Issue by jacobtang** [skymaze/pymediasoup#15]
the examples mediasoup.py demo code, use one videoTrack and one audioTrack, it seems that a videoTrack corresponds to a videoProducer, and a audioTrack corresponds to a audioProducer.
Init load device depends on self._tracks.
self._tracks.append(videoTrack)
self._tracks.append(audioTrack)
self._device = Device(
        handlerFactory=AiortcHandler.createFactory(tracks=self._tracks)
)

Thanks a lot!

**Comment by skymaze** [comment]
You can use multiple devices.

**Comment by skymaze** [comment]
mediasoup only extract first video and audio from sdp, see [pymediasoup](https://github.com/skymaze/pymediasoup/blob/bf6143429e3c9e23b073147a2f9cf02cf1d0751e/pymediasoup/handlers/sdp/common_utils.py#L24) and [mediasoup-client](https://github.com/versatica/mediasoup-client/blob/d3bcd19b42305b909c720033899efeccd23636dd/src/handlers/sdp/commonUtils.ts#L31)
