### ISSUE TITLE
How to connect with IceServer 

### ISSUE THREAD

**Issue by gabrielmatau79** [skymaze/pymediasoup#16]
I have been working on trying to connect a client from this library using an IceServer. It didn't work initially because the type defined for the IceServer parameter in the creation of the transports didn't match. We had to temporarily change into handler_interface.py file the type to iceServers So that we could add a list of Ice servers that we want to use.

iceServers: Optional[List[RTCIceServer]]

However, after encountering this problem, we have noticed that this function does not seem to be initializing correctly because when checking the RTC , the Ice connection is always in the 'new' state. My question is, was this feature ever tested? If there is a solution for this, could you please share it?

**Comment by skymaze** [comment]
Thanks, #17
