### ISSUE TITLE
hardware Acceleration support for video stream decode and encode

### ISSUE THREAD

**Issue by qwert3356** [skymaze/pymediasoup#19]
does pymediasoup supports GPU hardware Acceleration like nvdec nvenc?
Because my machine sometimes glitches when decoding frames from the consumer

i think it can be configure in aiortc or pyav, but i don't know where to start

**Comment by skymaze** [comment]
pyav use ffmpeg, you can build you ffmpeg with hardware acceleration [Using FFmpeg with NVIDIA GPU Hardware Acceleration](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html) and install [pyav](https://github.com/PyAV-Org/PyAV) use 

```
pip install av --no-binary av
```
