### ISSUE TITLE
Example poblem ask for help

### ISSUE THREAD

**Issue by fengkouxiaozhu** [skymaze/pymediasoup#4]
Hi :

   when I run python  mediasoup .py   xxxx , i want to open local webcam , but  I found in server  it can not proceduce correct video stream.   as follows 
   I wonder how can i USE THE Pymediasoup   produce the webcam video stream?
  videostreamTrack  does the  lib have the function of getusermedia  or getvideostream?

**Comment by skymaze** [comment]
You can use MediaPlayer: https://github.com/aiortc/aiortc/blob/main/examples/webcam/webcam.py
